ci(identity-hono): fix env variable issue

diff --git a/services/fat-identity-hono/cloudbuild.development.yaml b/services/fat-identity-hono/cloudbuild.development.yaml
--- a/services/fat-identity-hono/cloudbuild.development.yaml
+++ b/services/fat-identity-hono/cloudbuild.development.yaml
@@ -41,58 +41,45 @@ steps:
     id: push
 
   - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
-    args:
-      - '-c'
-      - |
-        RANDOM_SUFFIX=$(cat /dev/urandom | tr -dc 'a-z' | fold -w 3 | head -n 1)
-        echo "RANDOM_SUFFIX=$${RANDOM_SUFFIX}" >> /workspace/random_suffix.env
+    script: |
+      RANDOM_SUFFIX=$(cat /dev/urandom | tr -dc 'a-z' | fold -w 3 | head -n 1)
+      echo "RANDOM_SUFFIX=$${RANDOM_SUFFIX}" > /workspace/random_suffix.env
     id: generate-random-suffix
 
   - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
-    args:
-      - '-c'
-      - |
-        source /workspace/random_suffix.env
-        gcloud run deploy $_SERVICE_NAME \
-          --image=$_IMAGE_URL \
-          --labels=managed-by=gcp-cloud-build-deploy-cloud-run \
-          --labels=commit-sha=$COMMIT_SHA \
-          --labels=gcb-build-id=$BUILD_ID \
-          --labels=gcb-trigger-id=$_TRIGGER_ID \
-          --labels=short-sha=$SHORT_SHA \
-          --revision-suffix=commit-$SHORT_SHA-$$RANDOM_SUFFIX \
-          --no-traffic
-    waitFor: ['push']
+    script: |
+      source /workspace/random_suffix.env
+      gcloud run deploy $_SERVICE_NAME \
+        --image=$_IMAGE_URL \
+        --labels=managed-by=gcp-cloud-build-deploy-cloud-run \
+        --labels=commit-sha=$COMMIT_SHA \
+        --labels=gcb-build-id=$BUILD_ID \
+        --labels=gcb-trigger-id=$_TRIGGER_ID \
+        --labels=short-sha=$SHORT_SHA \
+        --revision-suffix=commit-$SHORT_SHA-$RANDOM_SUFFIX \
+        --no-traffic
+    waitFor: ['push', 'generate-random-suffix']
     id: deploy
 
   - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
     script: |
-      gcloud run services describe $_SERVICE_NAME \
-        --format="value(status.url)" > /workspace/deployer_environment_url
+      source /workspace/random_suffix.env
+      for i in {1..3}; do
+        echo "Attempt $i to update traffic..."
+        if gcloud run services update-traffic $_SERVICE_NAME \
+          --platform=managed \
+          --to-revisions=$_SERVICE_NAME-commit-$SHORT_SHA-$RANDOM_SUFFIX=100; then
+          echo "Traffic update successful"
+          exit 0
+        fi
+        echo "Traffic update failed, retrying in 10 seconds..."
+        sleep 10
+      done
+      echo "Failed to update traffic after 3 attempts"
+      exit 1
+    timeout: 300s  # 5m limit
     waitFor: ['deploy']
-    id: attach-url-to-report
-
-  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
     id: update-traffic
-    entrypoint: /bin/bash
-    args:
-      - '-c'
-      - |
-        source /workspace/random_suffix.env
-        for i in {1..3}; do
-          echo "Attempt $i to update traffic..."
-          if gcloud run services update-traffic $_SERVICE_NAME \
-            --platform=managed \
-            --to-revisions=$_SERVICE_NAME-commit-$SHORT_SHA-$$RANDOM_SUFFIX=100; then
-            echo "Traffic update successful"
-            exit 0
-          fi
-          echo "Traffic update failed, retrying in 10 seconds..."
-          sleep 10
-        done
-        echo "Failed to update traffic after 3 attempts"
-        exit 1
-    waitFor: ['deploy']
 
   - name: 'europe-west3-docker.pkg.dev/fat-core-dev/docker/gh-deployer:latest'
     env:
