ci: fix shell

diff --git a/services/fat-identity-hono/cloudbuild.development.yaml b/services/fat-identity-hono/cloudbuild.development.yaml
--- a/services/fat-identity-hono/cloudbuild.development.yaml
+++ b/services/fat-identity-hono/cloudbuild.development.yaml
@@ -47,29 +47,32 @@ steps:
     id: generate-random-suffix
 
   - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
-    script: |
-      . /workspace/random_suffix.env
-      # Construct the revision suffix
-      REVISION_SUFFIX="pr-${_PR_NUMBER}-commit-${SHORT_SHA}-$RANDOM_SUFFIX"
-      # Output the service name and revision suffix for debugging
-      echo "Service Name: $_SERVICE_NAME"
-      echo "Revision Suffix: $REVISION_SUFFIX"
-      # Ensure the revision suffix is valid
-      if [ ! "$REVISION_SUFFIX" =~ ^[a-z][a-z0-9-]*[a-z0-9]$ ]; then
-        echo "Invalid revision suffix: $REVISION_SUFFIX"
-        exit 1
-      fi
-      gcloud run deploy $_SERVICE_NAME \
-        --image=$_IMAGE_URL \
-        --labels=managed-by=gcp-cloud-build-deploy-cloud-run \
-        --labels=commit-sha=$COMMIT_SHA \
-        --labels=gcb-build-id=$BUILD_ID \
-        --labels=gcb-trigger-id=$_TRIGGER_ID \
-        --labels=short-sha=$SHORT_SHA \
-        --labels=pr-number=$_PR_NUMBER \
-        --revision-suffix=$REVISION_SUFFIX \
-        --no-traffic \
-        --tag=pr-$_PR_NUMBER
+    entrypoint: /bin/bash
+    args:
+      - '-c'
+      - |
+        . /workspace/random_suffix.env
+        # Construct the revision suffix
+        REVISION_SUFFIX="pr-${_PR_NUMBER:-0}-commit-${SHORT_SHA}-${RANDOM_SUFFIX}"
+        # Output the service name and revision suffix for debugging
+        echo "Service Name: $_SERVICE_NAME"
+        echo "Revision Suffix: $REVISION_SUFFIX"
+        # Ensure the revision suffix is valid
+        if [[ ! "$REVISION_SUFFIX" =~ ^[a-z][a-z0-9-]*[a-z0-9]$ ]]; then
+          echo "Invalid revision suffix: $REVISION_SUFFIX"
+          exit 1
+        fi
+        gcloud run deploy $_SERVICE_NAME \
+          --image=$_IMAGE_URL \
+          --labels=managed-by=gcp-cloud-build-deploy-cloud-run \
+          --labels=commit-sha=$COMMIT_SHA \
+          --labels=gcb-build-id=$BUILD_ID \
+          --labels=gcb-trigger-id=$_TRIGGER_ID \
+          --labels=short-sha=$SHORT_SHA \
+          --labels=pr-number=${_PR_NUMBER:-0} \
+          --revision-suffix=$REVISION_SUFFIX \
+          --no-traffic \
+          --tag=pr-${_PR_NUMBER:-0}
     waitFor: ['push', 'generate-random-suffix']
     id: deploy
 
