chore: rename fat-identity-hono to fat-identity
+ use fat-identity-hono as the main fat-identity
+ rename the old fat-identity to fat-identity-fastify
+ remove the cloudbuild and gh workflows and use hybrid as the main fat-identity (previously: fat-identity-hono) workflow

diff --git a/services/fat-identity/cloudbuild.development.yaml b/services/fat-identity/cloudbuild.development.yaml
--- a/services/fat-identity/cloudbuild.development.yaml
+++ b/services/fat-identity/cloudbuild.development.yaml
@@ -1,26 +1,4 @@
-# For info on gh-deployer, see: https://zentered.co/articles/preview-builds-with-cloud-run/
-
 steps:
-  - name: 'europe-west3-docker.pkg.dev/fat-core-dev/docker/gh-deployer:latest'
-    env:
-      - REPO_NAME=$REPO_NAME
-      - TRANSIENT_ENVIRONMENT=false
-      - DESCRIPTION=Deploying to Google Cloud Run
-      - ENVIRONMENT=$_GITHUB_ENVIRONMENT
-      - REF=$REF_NAME
-    args: [create]
-    waitFor: ['-']
-    id: create-report
-
-  - name: 'europe-west3-docker.pkg.dev/fat-core-dev/docker/gh-deployer:latest'
-    env:
-      - REPO_NAME=$REPO_NAME
-      - ENVIRONMENT=$_GITHUB_ENVIRONMENT
-      - REF=$REF_NAME
-    args: [in_progress]
-    waitFor: ['create-report']
-    id: report-in-progress
-
   - name: gcr.io/cloud-builders/docker
     args:
       - build
@@ -28,7 +6,7 @@ steps:
       - $_IMAGE_URL
       - .
       - '-f'
-      - services/fat-identity-hono/Dockerfile
+      - services/fat-identity/Dockerfile
     env:
       # Enable Docker BuildKit for faster builds
       - DOCKER_BUILDKIT=1
@@ -64,6 +42,32 @@ steps:
     waitFor: ['push', 'generate-random-suffix']
     id: deploy
 
+  # It might be necessary to use retries for this step. This was the case during the initial development but it might not be needed anymore.
+  # in any case, I'm leaving this as a comment for now.
+  # - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
+  #   entrypoint: /bin/bash
+  #   args:
+  #     - '-c'
+  #     - |
+  #       source /workspace/random_suffix.env
+  #       REVISION_SUFFIX="commit-$SHORT_SHA-$${RANDOM_SUFFIX}"
+  #       for i in {1..3}; do
+  #         echo "Attempt $i to update traffic..."
+  #         if gcloud run services update-traffic $_SERVICE_NAME \
+  #           --platform=managed \
+  #           --to-revisions=$_SERVICE_NAME-$${REVISION_SUFFIX}=100; then
+  #           echo "Traffic update successful"
+  #           exit 0
+  #         fi
+  #         echo "Traffic update failed, retrying in 10 seconds..."
+  #         sleep 10
+  #       done
+  #       echo "Failed to update traffic after 3 attempts"
+  #       exit 1
+  #   timeout: 300s  # 5m limit
+  #   waitFor: ['deploy']
+  #   id: update-traffic-with-retry
+
   - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
     entrypoint: /bin/bash
     args:
@@ -71,49 +75,24 @@ steps:
       - |
         source /workspace/random_suffix.env
         REVISION_SUFFIX="commit-$SHORT_SHA-$${RANDOM_SUFFIX}"
-        for i in {1..3}; do
-          echo "Attempt $i to update traffic..."
-          if gcloud run services update-traffic $_SERVICE_NAME \
-            --platform=managed \
-            --to-revisions=$_SERVICE_NAME-$${REVISION_SUFFIX}=100; then
-            echo "Traffic update successful"
-            exit 0
-          fi
-          echo "Traffic update failed, retrying in 10 seconds..."
-          sleep 10
-        done
-        echo "Failed to update traffic after 3 attempts"
-        exit 1
-    timeout: 300s  # 5m limit
+        gcloud run services update-traffic $_SERVICE_NAME \
+          --platform=managed \
+          --to-revisions=$_SERVICE_NAME-$${REVISION_SUFFIX}=100
     waitFor: ['deploy']
     id: update-traffic
-
-  - name: 'europe-west3-docker.pkg.dev/fat-core-dev/docker/gh-deployer:latest'
-    env:
-      - REPO_NAME=$REPO_NAME
-      - ENVIRONMENT=$_GITHUB_ENVIRONMENT
-      - REF=$REF_NAME
-    args: [success]
-    id: report-success
-
-  # TODO: How do we report failure?
-  # - name: 'europe-west3-docker.pkg.dev/fat-core-dev/docker/gh-deployer:latest'
-  #   env:
-  #     - REPO_NAME=$REPO_NAME
-  #     - ENVIRONMENT=$_GITHUB_ENVIRONMENT
-  #     - REF=$REF_NAME
-  #   args: [failure]
-  #   waitFor: ['create-report', 'report-in-progress', 'build', 'push', 'deploy', 'attach-url-to-report', 'update-traffic']
-  #   status: FAILURE
-  #   id: report-failure
 
 images: [$_IMAGE_URL]
 
 options:
-  # automatically map all the substitutions to environment variables
-  # which are available throughout the entire build
+  # Automatically map all the substitutions to environment variables, available throughout the entire build
+  # See https://cloud.google.com/build/docs/configuring-builds/substitute-variable-values#map_substitutions_automatically
   automapSubstitutions: true
   logging: CLOUD_LOGGING_ONLY
+
+  # Must be manually set due to the manual trigger.
+  # See https://cloud.google.com/build/docs/configuring-builds/substitute-variable-values#dynamic_substitutions
+  dynamicSubstitutions: true
+  
   env:
     - CLOUDSDK_CORE_DISABLE_PROMPTS=1 # Make all commands --quiet
     - CLOUDSDK_RUN_REGION=$_DEPLOY_REGION  # Use the same region for Cloud Run
@@ -121,7 +100,7 @@ options:
 substitutions:
   _TRIGGER_ID: ad037f34-04e2-45de-9b38-67ce0c0ab382
   _AR_HOSTNAME: europe-west3-docker.pkg.dev
-  _SERVICE_NAME: fat-identity-hono
+  _SERVICE_NAME: fat-identity
   _DEPLOY_REGION: europe-west3
   _GITHUB_ENVIRONMENT: development
   _AR_REPO_NAME: cloud-run-source-deploy
@@ -131,4 +110,4 @@ substitutions:
 tags:
   - gcp-cloud-build-deploy-cloud-run
   - gcp-cloud-build-deploy-cloud-run-managed
-  - fat-identity-hono
+  - fat-identity
